version: '3'
services:
  spring-boot-app:
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - db
  db:
    image: postgres:13.0
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_DB=inventorydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password